# Generated by Django 5.2.5 on 2026-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='organization_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='organization_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='organization_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
