# Generated by Django 5.2.5 on 2026-01-23 08:54

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venuearea',
            constraint=models.CheckConstraint(condition=models.Q(('max_capacity_total__gte', django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('max_capacity_seated'), 0), '+', django.db.models.functions.comparison.Coalesce(models.F('max_capacity_standing'), 0)))), name='capacity_not_exceed_total'),
        ),
    ]
