# Generated by Django 5.2.5 on 2026-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Konsert'), ('festival', 'Festival')], default='concert', help_text='Type arrangement: konsert eller festival', max_length=20),
        ),
    ]
