# Generated by Django 5.2.5 on 2026-02-05 16:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStandingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sold', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_allocations', to='events.event')),
                ('venue_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_allocations', to='events.venuearea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'venue_area'), name='unique_standing_allocation_per_event_area')],
            },
        ),
    ]
