# Generated by Django 5.2.5 on 2026-01-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venuearea_capacity_not_exceed_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='events.address'),
        ),
        migrations.AlterField(
            model_name='venuearea',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='events.venue'),
        ),
        migrations.AddConstraint(
            model_name='venuearea',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_venue_area_name'),
        ),
    ]
