# Generated by Django 5.2.5 on 2026-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Bilde-URL'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Bynavn'),
        ),
    ]
