# Generated by Django 5.2.5 on 2026-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_city_image_url_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='performer',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='events', to='events.performer'),
        ),
    ]
