# Generated by Django 5.2.5 on 2026-01-29 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuearea',
            name='max_capacity_seated',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venuearea',
            name='max_capacity_standing',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venuearea',
            name='max_capacity_total',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('venue_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='events.venuearea')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.row')),
            ],
        ),
        migrations.CreateModel(
            name='EventSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_seats', to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_seats', to='events.seat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='row',
            constraint=models.UniqueConstraint(fields=('venue_area', 'name'), name='unique_row_in_venue_area'),
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('venue_area', 'name')},
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('row', 'number'), name='unique_seat_in_row'),
        ),
        migrations.AddConstraint(
            model_name='eventseat',
            constraint=models.UniqueConstraint(fields=('event', 'seat'), name='unique_seat_per_event'),
        ),
    ]
