# Generated by Django 5.2.5 on 2026-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_performer_event_performer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='performer',
        ),
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.performer'),
        ),
    ]
