# Generated by Django 5.2.5 on 2026-01-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_venuearea_max_capacity_seated_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='row',
            unique_together=set(),
        ),
    ]
