# Generated by Django 5.2.5 on 2026-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_performer_event_performers'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='performer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='performers/'),
        ),
        migrations.AddField(
            model_name='performer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
