# Generated by Django 5.2.5 on 2026-03-05 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_performer_bio_performer_genre_performer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_event_id', models.IntegerField()),
                ('organizer_name', models.CharField(max_length=255)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('performers_list', models.TextField(blank=True, help_text='Kommaseparert liste over artister')),
                ('event_type', models.CharField(choices=[('concert', 'Konsert'), ('festival', 'Festival')], default='concert', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Archived Event',
                'verbose_name_plural': 'Archived Events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='Путь к изображению', max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
                ('archived_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.archivedevent')),
            ],
        ),
    ]
