# Generated by Django 5.2.5 on 2026-03-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_archivedevent_archivedeventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Om arrangementet er arkivert'),
        ),
        migrations.AlterField(
            model_name='archivedeventimage',
            name='image_path',
            field=models.CharField(help_text='Sti til bildet', max_length=500),
        ),
    ]
