# Generated by Django 5.2.5 on 2026-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('hiphop', 'Hip-Hop'), ('electronic', 'Electronic'), ('classical', 'Classical'), ('folk', 'Folk'), ('r&b', 'R&B'), ('country', 'Country'), ('metal', 'Metal'), ('other', 'Other')], max_length=20),
        ),
    ]
