# Generated by Django 5.2.5 on 2026-02-17 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
