# Generated by Django 5.2.5 on 2026-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(choices=[('ordinary', 'Ordinær'), ('vip', 'VIP'), ('student', 'Student'), ('child', 'Barn'), ('senior', 'Senior')], max_length=100),
        ),
    ]
